### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kimfy** [Tschipp/BuildersBag#1]
Hi,

I added BuildersBag to my server installation of Enigmatica 2 Expert. The server crashes upon loading up. Client works fine. Maybe there is some client code running on the server? Rendering stuff etc.

Relevant trace can be found on line 34 in the following Pastebin.

Crash report: https://pastebin.com/A6QCejmi

**Comment by SeriousCreeper** [comment]
Same for me with my custom pack: https://pastebin.com/M6DpND5d

**Comment by Tschipp** [comment]
Oops, client code on the server, classic
