### ISSUE TITLE
[Bug] Excess Crafting

### ISSUE THREAD

**Issue by mxnmnm** [Tschipp/BuildersBag#11]
**Expected Behavior**
No excess crafting to be made

**Actual Behavior**
Cobble slabs are being crafted when placing cobblestone that's being crafted from compressed cobble. This doesn't really matter in game but since it's probably unintended I figured you should know about it in case it's caused by some deeper issue with the crafting module.

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**
1.12.2 and version 1.1.1.11 and I have the project e addon
If you need the versions for other things let me know but I'm to lazy to look for the rest of them but they should be the latest as of 5/16/2020

Here's a video of it in action:
https://www.youtube.com/watch?v=MQj97NyQGJE&feature=youtu.be

**Comment by Tschipp** [comment]
Yeah this is one down-side of the current system. I will reconsider this.
