### ISSUE TITLE
[Bug] Opening controls crashes game with this mod

### ISSUE THREAD

**Issue by PahviMasiina** [Tschipp/BuildersBag#15]
**Expected Behavior**
Clicking 'Controls' with this mod should open controls menu.
**Actual Behavior**
It crashes the game.

**Steps to Reproduce**
1. Launch Minecraft with this mod.
2. Press 'Controls'.
3. Watch the game crash.

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**
Minecraft: 1.12.2.
Builder's Bag: 1.1.1.11.
Forge: 14.23.5.2847 and 14.23.5.2854 both tested with similar results.
Single player and main menu both.

**Screenshots encouraged**
No screenshot but crash log.
[crash-2020-05-24_17.35.37-client.txt](https://github.com/Tschipp/BuildersBag/files/4673781/crash-2020-05-24_17.35.37-client.txt)

**Comment by Tschipp** [comment]
Are you using any other mods?

**Comment by PahviMasiina** [comment]
No, also the configs are fresh.

**Comment by Tschipp** [comment]
Strange. I'll try it with your exact versions later.
