### ISSUE TITLE
[Bug] Coal/Charcoal missing textures

### ISSUE THREAD

**Issue by mxnmnm** [Tschipp/BuildersBag#16]
**Expected Behavior**
Coal/charcoal having normal textures

**Actual Behavior**
Coal/charcoal have missing textures

**Steps to Reproduce**
Find coal/charcoal

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**
Only happens with version 1.2.0.13
I do have the project e addon along with every single mod builder's bags adds compat for with exception with chisels and bits and linear

**Screenshots encouraged**
![2020-05-31_18 09 03](https://user-images.githubusercontent.com/8508976/83367612-48b67780-a36a-11ea-92f2-68b0f8c5addb.png)

**Comment by Tschipp** [comment]
Oh crap yeah I forgot about that
