### ISSUE TITLE
[Bug] Cannot Craft Fences

### ISSUE THREAD

**Issue by Darkosto** [Tschipp/BuildersBag#17]
**Expected Behavior**
I would like to craft a fence

**Actual Behavior**
I cannot craft a fence

**Steps to Reproduce**
-5. Be born
-4. Buy house/apartment (or live in basement of family)
-3. Buy a computer
-2. Plug in said computer
-1. get electricity
0. Turn on computer and run minecraft
1. Enable crafting module
2. add items to bag and/or player inventory
3. Pick fence block with middle mouse button
4. Attempt to place fences
5. Profit???
6. I think this might not an actual bug but a pack thing

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**

**Screenshots encouraged**
![SS](https://user-images.githubusercontent.com/10309699/84553507-44268300-acc9-11ea-907a-bcb7aa2c3383.PNG)

**Comment by Darkosto** [comment]
I'm dumb. Not bug!

**Comment by Tschipp** [comment]
Lolwut
