### ISSUE TITLE
[Bug] Crash when attempting to utilize with Omnifactory Modpack

### ISSUE THREAD

**Issue by DevJRoc** [Tschipp/BuildersBag#22]
**Expected Behavior**
No issues with load

**Actual Behavior**
An exception occurs when loading
_net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: tschipp/buildersbag/common/item/BuildersBagItem_

Upon review of the logs, some lines like this:
_[18:51:43] [Client thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber tschipp.buildersbag.common.BuildersBagRegistry for modid buildersbag
java.lang.NoClassDefFoundError: tschipp/buildersbag/common/item/BuildersBagItem_

[latest.log](https://github.com/Tschipp/BuildersBag/files/4905853/latest.log)

Is this an issue with the forge version, or one of the dependencies?

**Steps to Reproduce**
Setup latest version of Omnifactory from Twitch
Apply community patches for Applied Energistics, Gregtech, Shadows of Greg
Add buildeersbag and launch

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**
Minecraft Version: 1.12.2
[FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2
buildersbag-1.12.2-1.2.2.16.jar
Baubles-1.12-1.5.2.jar
Chisel-MC1.12.2-1.0.2.45.jar
CraftTweaker2-1.12-4.1.20.562.jar
LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar

**Comment by Tschipp** [comment]
That is very odd... could you try updating LittleTiles (and CreativeCore)?

**Comment by ALongStringOfNumbers** [comment]
Hello,

Upon testing this against a branch where LittleTiles and CreativeCore are updated to 1.5.0-pre199_34 and 1.10.16 respectively (Specific branch is https://github.com/OmnifactoryDevs/Omnifactory/pull/476 ), I did not crash when loading the pack.

Other updates to note in this branch are CraftTweaker being 4.1.20.576.

**Comment by Tschipp** [comment]
that's good, right? Sadly I can't do better version checks for LittleTiles and CC because they use an unsupported version format. "1.5.0-preX" is still just 1.5.0 internally. But version 34 (or up) were used in development. Can I close this?

**Comment by DevJRoc** [comment]
Hey thanks for confirming the version incompat root cause! Closing this issue
