### ISSUE TITLE
[Bug] Minecraft fails to load then crashes when Building Gadgets added to MC Eternal 1.3.7

### ISSUE THREAD

**Issue by wcarroll4** [Tschipp/BuildersBag#26]
**Expected Behavior**

Minecraft fully loads and reaches main menu.

**Actual Behavior**

Minecraft fails to load then crashes when Building Gadgets added to MC Eternal 1.3.7.1. I have also added Project E and 
Builder's Bag - ProjectE Addon to the pack. I have attached the latest crash report if that helps:

[crash-2020-08-26_12.29.08-client.txt](https://github.com/Tschipp/BuildersBag/files/5131411/crash-2020-08-26_12.29.08-client.txt)

I am loading the game through MultiMC. I've allocated 8gb of RAM to the modpack. My Java arguments are as follows:

-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Because this modpack uses CraftTweaker2 version 1.12-4.1.20, it's possible that this is related to issue #20 

**Steps to Reproduce**
Add Builder's Bag, ProjectE, and Builder's Bag - ProjectE Addon to the MC Eternal Modpack, version 1.3.7, then attempt to load the game.

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**

Minecraft: 1.12.2
MC Eternal: 1.3.7.1
Builder's Bag: 1.12.2-1.3.0.22
Builder's Bag - ProjectE Addon: 1.12.2-1.1.0.8
ProjectE: 1.12.2-PE1.4.1

Single Player

**Screenshots encouraged**

**Comment by wcarroll4** [comment]
This could also be due to the latest version of MC Eternal using an older version of CreativeCore (CreativeCore_v1.10.9_mc1.12.2) and an older version of LittleTiles (LittleTiles_v1.5.0-pre199_19_mc1.12.2). I'm going to test updating those and see if it loads successfully.

**Comment by wcarroll4** [comment]
Well, on the one hand updating those two mods allows the game to load fully and a new world to be created and entered with Building Bags et al added. On the other hand, updating those two mods etc and entering a new world results in the player being trapped and unable to move, twitching rapidly up and down as though you are inside of a block, and your inventory fails to completely load with all starting objects half-way rendered.

Sigh. I'm figuring this is an issue with inter-version compatibility so I'll go ahead and close this as I don't think it's a problem on your end.

**Comment by Tschipp** [comment]
Hmm, I'm sorry to hear this. I sadly can't provide exact specifications for the version of Creative Core and LittleTiles, as they use an incompatible version format. I would try downgrading LT and CC until it works, I think pre_199_30 should work, maybe even earlier.
