### ISSUE TITLE
[Bug] 1.12.2 Serverside Crash - Seems to be trying to load client code server side related to "bag wheel"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Tschipp/BuildersBag#28]
**Expected Behavior**

All code is functional

**Actual Behavior**

Crashes on load. It's trying to load the gui "Bag Wheel" server side.

**Steps to Reproduce**

Dunno.

**Version of Minecraft, version of Builder's Bag, version of Addons, version of other Builder's Bag-compatible mods, Single Player or Server**

* Minecraft 1.12.2
* Baubles-1.12-1.5.2.jar
* buildersbag-1.12.2-1.4.0.23.jar 
* BuildingGadgets-2.8.4.jar
* Chisel-MC1.12.2-1.0.2.45.jar 
* chiselsandbits-14.33.jar
* CraftTweaker2-1.12-4.1.20.586.jar
* CreativeCore_v1.10.34_mc1.12.2.jar
* LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar

**Screenshots encouraged**

"Not possible it happened serverside."

**Logs**

Cherry Picked - https://gist.github.com/P3rf3ctXZer0/b3fd2b75f3b77b09885966bd6e0d93ff
Crashlog - https://gist.github.com/P3rf3ctXZer0/d8947dd8326c9ea53dab47800636fc22
Latest Log - https://gist.github.com/P3rf3ctXZer0/cd69ea3098f96d67c932ae1cc4274b59

**Comment by Tschipp** [comment]
thanks, will fix asap

**Comment by Tschipp** [comment]
Fix out now
