### ISSUE TITLE
[Suggestion] Weight in randomness module

### ISSUE THREAD

**Issue by kimfy** [Tschipp/BuildersBag#4]
Hi,

Setting a higher weight for specific blocks would be quite useful. I often build roads where I have one main block and others that I place far less often. One could select a block in the bag and a +/- sign at the top would adjust the weight. Maybe show the weight as the standard itemstack count number to go with the theme of Minecraft.

Thanks

**Comment by Tschipp** [comment]
This is actually possible already: Just spread out the blocks you want more or less of on different stacks. So if you want 50% Grass, 20% Gravel and 30% Cobblestone, have 5 stacks of Grass, 2 Stacks of Gravel and 3 Stacks of Cobblestone in the bag (they don't need to be full stacks).
