### ISSUE TITLE
[Suggestion] Botania support?

### ISSUE THREAD

**Issue by DoomRater** [Tschipp/BuildersBag#6]
Botania's Rod of the Shifting Crust will already pull from inventory containers in one's inventory if it can find them.  By default, it'll check for a Hand of Ender and pull from one's vanilla Ender Chest, or rods that create blocks if they're in a valid inventory (or in the ender chest when you have Hand of Ender).  I'm just imagining pulling from rods for blocks, or letting the Rod of the Shifting Crust use what's in the builder's bag as well.

Er, now that I think of it, just being able to stuff a Rod of the Lands in there and get randomized dirt with a chisel operation, or a Rod of the Depths dumping cobble everywhere would be super cool to surprise the botanists on my server with.

**Comment by Tschipp** [comment]
Yep, already done that in dev.
