### ISSUE TITLE
Crafting Module Not Working All of the Time

### ISSUE THREAD

**Issue by mxnmnm** [Tschipp/BuildersBag#7]
For the crafting the module doesn't like it when there are multiple steps. So I can use planks to place stairs but I can't use logs to place stairs. Sometimes it straight up refuses to work like with extra utilities compressed cobble (just regular compressed so nothing insane)

The chisel module is straight up broken and has not worked for me once. I'm assuming the way it works is I can choose a specific type of chisel block and I place the raw material in the bag and it places down the chisel design I've chosen.

This is in a largely modded instance so I'll probably post the modlist on here a bit later because I'm sure it's some weird mod interaction.

**Comment by Tschipp** [comment]
hmm and all modules are enabled? And you have a chisel in the chisel module? Could you make a small video or gif showing what's happening?

**Comment by mxnmnm** [comment]
Oh I didn't realize you needed a chisel lololol, yea it works fine but the recipes are still broken unless I need to do something to get them to work.

**Comment by Tschipp** [comment]
Can you show me a video? It's really hard to tell what is wrong otherwise.
